# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom_enfant', models.CharField(max_length=200)),
                ('nom_enfant', models.CharField(max_length=200)),
                ('ecole', models.CharField(max_length=200)),
                ('position_football', models.CharField(max_length=200)),
                ('date_inscription', models.DateTimeField()),
                ('age', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom_parent', models.CharField(max_length=200)),
                ('nom_parent', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='enfant',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.Parent'),
        ),
    ]
