# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfant',
            name='a_deja_paye',
            field=models.BooleanField(default=False),
        ),
    ]
